apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.io
spec:
  latestResourceSchemas:
  - v240715-7835dfb5a.workspacetypes.tenancy.kcp.io
  - v240731-370e3c746.workspaces.tenancy.kcp.io
  maximalPermissionPolicy:
    local: {}
status: {}
