apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.io
spec:
  maximalPermissionPolicy:
    local: {}
  resources:
  - group: tenancy.kcp.io
    name: workspaceauthenticationconfigurations
    schema: v250802-1b3cd3d0d.workspaceauthenticationconfigurations.tenancy.kcp.io
    storage:
      crd: {}
  - group: tenancy.kcp.io
    name: workspaces
    schema: v250421-25d98218b.workspaces.tenancy.kcp.io
    storage:
      crd: {}
  - group: tenancy.kcp.io
    name: workspacetypes
    schema: v250725-9ac3dc4fe.workspacetypes.tenancy.kcp.io
    storage:
      crd: {}
status: {}
