apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.io
spec:
  maximalPermissionPolicy:
    local: {}
  resources:
  - group: tenancy.kcp.io
    name: workspaces
    schema: v241020-fce06d31d.workspaces.tenancy.kcp.io
    storage:
      crd: {}
  - group: tenancy.kcp.io
    name: workspacetypes
    schema: v250325-c1864de17.workspacetypes.tenancy.kcp.io
    storage:
      crd: {}
status: {}
