apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.io
spec:
  latestResourceSchemas:
  - v241020-fce06d31d.workspaces.tenancy.kcp.io
  - v250325-c1864de17.workspacetypes.tenancy.kcp.io
  maximalPermissionPolicy:
    local: {}
status: {}
