apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: cache.kcp.io
spec:
  resources:
  - group: cache.kcp.io
    name: cachedresourceendpointslices
    schema: v250604-36e6abf17.cachedresourceendpointslices.cache.kcp.io
    storage:
      crd: {}
  - group: cache.kcp.io
    name: cachedresources
    schema: v250830-080348246.cachedresources.cache.kcp.io
    storage:
      crd: {}
status: {}
