name: Daily Image Cleanup
on:
  # every day at 01:30am
  schedule:
    - cron: '30 1 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # tag=v1.0.16
        with:
          older-than: 1 month
          owner: kcp-dev
          repository: kcp
          package: kcp-prs
          delete-tags: '^pr-\d+-[a-z0-9]+-[a-z0-9]+$'
          use-regex: true
          dry-run: true
